apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-test
  namespace: cygni-builds
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: kaniko-builder
      restartPolicy: Never
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          command:
            - sh
            - -c
            - |
              git clone https://github.com/GoogleContainerTools/kaniko.git /workspace
              cd /workspace
              # Use the integration test example
              cp -r integration/dockerfiles/simple/* .
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=/workspace"
            - "--dockerfile=/workspace/Dockerfile"
            - "--destination=localhost:5000/test-build:latest"
            - "--insecure"
            - "--skip-tls-verify"
            - "--cache=true"
            - "--cache-repo=localhost:5000/cache"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: docker-config
              mountPath: /kaniko/.docker
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: workspace
          emptyDir: {}
        - name: docker-config
          configMap:
            name: docker-config
            items:
              - key: config.json
                path: config.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: cygni-builds
data:
  config.json: |
    {
      "auths": {
        "localhost:5000": {
          "auth": "dGVzdDp0ZXN0"
        }
      }
    }