kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cygni-test
nodes:
  - role: control-plane
    extraPortMappings:
      # Local registry port
      - containerPort: 5000
        hostPort: 5000
        protocol: TCP
    extraMounts:
      # Mount docker socket for Kaniko
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
---
# Local Docker registry for testing
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:5000"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"