version: "3.8"

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cloudexpress_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 3s
      retries: 5

  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-test:
    build: .
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://test:test@test-db:5432/cloudexpress_test
      REDIS_URL: redis://test-redis:6379
      JWT_SECRET: test-secret
      STRIPE_SECRET_KEY: sk_test_dummy
      PORT: 3001
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    command: npm run test:e2e
