{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cygni.fullname" . }}-api-secrets
  labels:
    {{- include "cygni.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "cygni.postgresqlUrl" . }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ include "cygni.redisUrl" . }}
  {{- end }}
  # JWT secret should be provided via external secret management
  jwt-secret: {{ .Values.api.jwtSecret | default (randAlphaNum 32) | quote }}
{{- end }}